-keep class org.cashudevkit.** { *; }
-keep class uniffi.** { *; }
-keep class com.sun.jna.** { *; }
-keep class kotlin.coroutines.** { *; }
-dontwarn org.cashudevkit.**
-dontwarn com.sun.jna.**
-dontwarn java.awt.**
-keep class org.fedimint.** { *; }
-dontwarn org.fedimint.**
